mon.dl: ofiles/mon.o
    absload -s -x -T 1000 -o mon.dl ofiles/mon.o

ofiles/mon.o: ofiles/main.o ofiles/io.o ofiles/ram.o ofiles/cmdtbl.o ofiles/except.o ofiles/go.o
    blink ofiles/main.o ofiles/io.o ofiles/cmdtbl.o ofiles/except.o ofiles/go.o ofiles/ram.o to ofiles/mon.o

ofiles/main.o: main.asm mon.i
    genim2 -oofiles/main.o main.asm -L

ofiles/io.o: io.asm
    genim2 -oofiles/io.o io.asm -L

ofiles/ram.o: ram.asm mon.i
    genim2 -oofiles/ram.o ram.asm -L

ofiles/cmdtbl.o: cmdtbl.asm
    genim2 -oofiles/cmdtbl.o cmdtbl.asm -L

ofiles/except.o: except.asm
    fixrc assem -o ofiles/except.o except.asm

ofiles/go.o: go.asm
    genim2 -oofiles/go.o go.asm -L
