/******************************************************************************
*  Generated by PSoC Designer ver 4.3  b1884 : 23 June, 2006
******************************************************************************/
#include <m8c.h>
// D_TX address and mask defines
#pragma	ioport	D_TX_Data_ADDR:	0x0
BYTE			D_TX_Data_ADDR;
#pragma	ioport	D_TX_DriveMode_0_ADDR:	0x100
BYTE			D_TX_DriveMode_0_ADDR;
#pragma	ioport	D_TX_DriveMode_1_ADDR:	0x101
BYTE			D_TX_DriveMode_1_ADDR;
#pragma	ioport	D_TX_DriveMode_2_ADDR:	0x3
BYTE			D_TX_DriveMode_2_ADDR;
#pragma	ioport	D_TX_GlobalSelect_ADDR:	0x2
BYTE			D_TX_GlobalSelect_ADDR;
#pragma	ioport	D_TX_IntCtrl_0_ADDR:	0x102
BYTE			D_TX_IntCtrl_0_ADDR;
#pragma	ioport	D_TX_IntCtrl_1_ADDR:	0x103
BYTE			D_TX_IntCtrl_1_ADDR;
#pragma	ioport	D_TX_IntEn_ADDR:	0x1
BYTE			D_TX_IntEn_ADDR;
#define D_TX_MASK 0x4
// V_TX address and mask defines
#pragma	ioport	V_TX_Data_ADDR:	0x0
BYTE			V_TX_Data_ADDR;
#pragma	ioport	V_TX_DriveMode_0_ADDR:	0x100
BYTE			V_TX_DriveMode_0_ADDR;
#pragma	ioport	V_TX_DriveMode_1_ADDR:	0x101
BYTE			V_TX_DriveMode_1_ADDR;
#pragma	ioport	V_TX_DriveMode_2_ADDR:	0x3
BYTE			V_TX_DriveMode_2_ADDR;
#pragma	ioport	V_TX_GlobalSelect_ADDR:	0x2
BYTE			V_TX_GlobalSelect_ADDR;
#pragma	ioport	V_TX_IntCtrl_0_ADDR:	0x102
BYTE			V_TX_IntCtrl_0_ADDR;
#pragma	ioport	V_TX_IntCtrl_1_ADDR:	0x103
BYTE			V_TX_IntCtrl_1_ADDR;
#pragma	ioport	V_TX_IntEn_ADDR:	0x1
BYTE			V_TX_IntEn_ADDR;
#define V_TX_MASK 0x8
// D_RX address and mask defines
#pragma	ioport	D_RX_Data_ADDR:	0x0
BYTE			D_RX_Data_ADDR;
#pragma	ioport	D_RX_DriveMode_0_ADDR:	0x100
BYTE			D_RX_DriveMode_0_ADDR;
#pragma	ioport	D_RX_DriveMode_1_ADDR:	0x101
BYTE			D_RX_DriveMode_1_ADDR;
#pragma	ioport	D_RX_DriveMode_2_ADDR:	0x3
BYTE			D_RX_DriveMode_2_ADDR;
#pragma	ioport	D_RX_GlobalSelect_ADDR:	0x2
BYTE			D_RX_GlobalSelect_ADDR;
#pragma	ioport	D_RX_IntCtrl_0_ADDR:	0x102
BYTE			D_RX_IntCtrl_0_ADDR;
#pragma	ioport	D_RX_IntCtrl_1_ADDR:	0x103
BYTE			D_RX_IntCtrl_1_ADDR;
#pragma	ioport	D_RX_IntEn_ADDR:	0x1
BYTE			D_RX_IntEn_ADDR;
#define D_RX_MASK 0x10
// V_RX address and mask defines
#pragma	ioport	V_RX_Data_ADDR:	0x0
BYTE			V_RX_Data_ADDR;
#pragma	ioport	V_RX_DriveMode_0_ADDR:	0x100
BYTE			V_RX_DriveMode_0_ADDR;
#pragma	ioport	V_RX_DriveMode_1_ADDR:	0x101
BYTE			V_RX_DriveMode_1_ADDR;
#pragma	ioport	V_RX_DriveMode_2_ADDR:	0x3
BYTE			V_RX_DriveMode_2_ADDR;
#pragma	ioport	V_RX_GlobalSelect_ADDR:	0x2
BYTE			V_RX_GlobalSelect_ADDR;
#pragma	ioport	V_RX_IntCtrl_0_ADDR:	0x102
BYTE			V_RX_IntCtrl_0_ADDR;
#pragma	ioport	V_RX_IntCtrl_1_ADDR:	0x103
BYTE			V_RX_IntCtrl_1_ADDR;
#pragma	ioport	V_RX_IntEn_ADDR:	0x1
BYTE			V_RX_IntEn_ADDR;
#define V_RX_MASK 0x20
