update=25/02/2013 13:02:31
version=1
last_client=kicad
[eeschema]
version=1
LibDir=
NetFmt=1
HPGLSpd=20
HPGLDm=15
HPGLNum=1
offX_A4=0
offY_A4=0
offX_A3=0
offY_A3=0
offX_A2=0
offY_A2=0
offX_A1=0
offY_A1=0
offX_A0=0
offY_A0=0
offX_A=0
offY_A=0
offX_B=0
offY_B=0
offX_C=0
offY_C=0
offX_D=0
offY_D=0
offX_E=0
offY_E=0
RptD_X=0
RptD_Y=100
RptLab=1
LabSize=60
[eeschema/libraries]
LibName1=/home/doug/Documents/DougsPCBDesigns/KiCAD/library/DougsSch
LibName2=power
LibName3=device
LibName4=C:/Users/DGilliland.AACISD/Documents/PCB Designs/DougsPCBDesigns/KiCAD/library/DougsSch
[cvpcb]
version=1
NetIExt=net
[cvpcb/libraries]
EquName1=devcms
[pcbnew]
version=1
PadDrlX=320
PadDimH=600
PadDimV=600
BoardThickness=630
TxtPcbV=800
TxtPcbH=600
TxtModV=600
TxtModH=600
TxtModW=120
VEgarde=100
DrawLar=150
EdgeLar=150
TxtLar=120
MSegLar=150
LastNetListRead=IntegTheremin.net
[pcbnew/libraries]
LibDir=
LibName1=/home/doug/Documents/DougsPCBDesigns/KiCAD/modules/dougsLib
LibName2=/home/doug/Documents/DougsPCBDesigns/KiCAD/modules/smd_resistors
LibName3=dip_sockets
LibName4=pin_array
LibName5=libcms
LibName6=/home/doug/Documents/DougsPCBDesigns/KiCAD/modules/audioamp386
LibName7=/home/doug/Documents/DougsPCBDesigns/KiCAD/modules/smd_dil
LibName8=discret
LibName9=/home/doug/Documents/DougsPCBDesigns/KiCAD/modules/ftdichip-1
LibName10=C:/Users/DGilliland.AACISD/Documents/PCB Designs/DougsPCBDesigns/KiCAD/modules/dougsLib
LibName11=IntegTheremin
[general]
version=1
