# Caution: this file may regenerated by SOPC Builder.  User edits will be lost.
project_open -current_revision G:/FLASH/NIOS_SDRAM.qpf
set_global_assignment -name VHDL_FILE altera_europa_support.vhd
project_close