update=8/16/2017 8:44:38 PM
last_client=kicad
[general]
version=1
[pcbnew]
version=1
PadDrlX=320
PadDimH=600
PadDimV=600
BoardThickness=630
TxtPcbV=800
TxtPcbH=600
TxtModV=600
TxtModH=600
TxtModW=120
VEgarde=100
DrawLar=150
EdgeLar=150
TxtLar=120
MSegLar=150
LastNetListRead=HVDigitalPot2.net
[pcbnew/libraries]
LibName1=connect
LibName2=discret
LibName3=pin_array
LibName4=/home/doug/Documents/DougsPCBDesigns/KiCAD/modules/dougsLib
LibName5=/home/doug/Documents/DougsPCBDesigns/KiCAD/modules/smd_dil
LibName6=/home/doug/Documents/DougsPCBDesigns/KiCAD/modules/adafruit
LibName7=/home/doug/Documents/DougsPCBDesigns/KiCAD/modules/smd_capacitors
LibName8=/home/doug/Documents/DougsPCBDesigns/KiCAD/modules/smd_resistors
LibDir=/home/doug/PCB Designs/KiCAD/modules
[cvpcb]
version=1
NetIExt=net
[cvpcb/libraries]
EquName1=devcms
[eeschema]
version=1
LibDir=/home/doug/PCB Designs/KiCAD/library
[eeschema/libraries]
LibName1=HVDigitalPot2-rescue
LibName2=power
LibName3=conn
LibName4=device
LibName5=/home/doug/Documents/DougsPCBDesigns/KiCAD/library/DougsSch
