# SPDX-FileCopyrightText: 2017 Scott Shawcroft, written for Adafruit Industries
#
# SPDX-License-Identifier: MIT

name: Build CI

on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        export GITHUB_CONTEXT
        printenv GITHUB_CONTEXT
    - name: Translate Repo Name For Build Tools filename_prefix
      id: repo-name
      run: |
        echo ::set-output name=repo-name::$(
        echo ${{ github.repository }} |
        awk -F '\/' '{ print tolower($2) }' |
        tr '_' '-'
        )
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Versions
      run: |
        python3 --version
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Install deps
      run: |
        sudo apt-get install gettext
        pip install -r requirements.txt
        pip install pre-commit
    - name: Library version
      run: git describe --dirty --always --tags
    - name: Pre-commit hooks
      run: |
        pre-commit run --all-files
    - name: Build assets
      run: circuitpython-build-bundles --filename_prefix ${{ steps.repo-name.outputs.repo-name }} --library_location libraries --library_depth 2 --package_folder_prefix "adafruit_, asyncio"
    - name: Build docs
      working-directory: docs
      run: sphinx-build -E -W -b html . _build/html
    - name: Setup problem matchers
      uses: adafruit/circuitpython-action-library-ci-problem-matchers@v1
